sudo: required 

services:
  - docker


env:
  OWNER: cnych
  IMAGE_NAME: productaste
  QNAME: ${OWNER}/${IMAGE_NAME}
  IMAGE_VERSION: v1.${TRAVIS_BUILD_NUMBER}
  BUILD_TAG : ${QNAME}:${IMAGE_VERSION}
  LATEST_TAG: ${QNAME}:latest


# todo, test 

install:
  - echo "1. install"


script:
  - echo "2. build docker image"
  - docker --version
  - docker build -t ${BUILD_TAG} .
  - docker tag ${BUILD_TAG} ${LATEST_TAG}

after_success:
  - echo "3. push docker image"
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
  - docker push ${BUILD_TAG}
  - docker push ${LATEST_TAG}

