sudo: required  #is required to use docker service in travis

services:
  - docker

env:
  OWNER: cnych
  IMAGE_NAME: productaste
  QNAME: ${OWNER}/${IMAGE_NAME}
  IMAGE_VERSION: v1.${TRAVIS_BUILD_NUMBER}
  BUILD_TAG: ${QNAME}:${IMAGE_VERSION}
  LATEST_TAG: ${QNAME}:latest

install:
  - echo ${BUILD_TAG}
  - echo "1. install"

script:
  - echo "2. build docker image"
  - echo ${BUILD_TAG}
  - echo ${LATEST_TAG}
  - docker --version
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
  - docker build -t ${BUILD_TAG} .
  - docker tag ${BUILD_TAG} ${LATEST_TAG}

after_success:
  - echo "3. push docker image"
  - docker push ${BUILD_TAG}
  - docker push ${LATEST_TAG}

notifications:
  email:
    recipients:
      - ych_1024@163.com
    on_success: never # default: change
    on_failure: always # default: always

deploy:
  provider: script
  script: deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^staging|production$
