version: '2'

services:
  drone-server:
    image: drone/drone:0.8

    ports:
      - 80:8000
      - 9000
    volumes:
      - /tmp/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://localhost
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=6ad96ea0e1789a232a74
      - DRONE_GITHUB_SECRET=f1067e2dd3ddf094d5d3c0c4b500a570da5dcb2d
      - DRONE_SECRET=haimaxy

  drone-agent:
    image: drone/agent:0.8

    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=haimaxy
